### ISSUE TITLE
stupid question?

### ISSUE THREAD

**Issue by StrykeSlammerII** [EMBTonkin/DAL9001#7]
just gonna rant because I'm sleepy and will probably find the answer quickly once I've slept:

```
ArrayList<String[]> colors = new ArrayList<String[]>(67); // there's still just 67 colors, right?

try
{
    String[] output = new String[2];
    String line = null;
    while( (line = reader.readLine()) != null )
    {
        output[0] = line.split(",")[1];
        output[1] = line.split(",")[2];  // slightly inefficient but we can tweak that later if load times are REALLY a problem. --SS2
        colors.add( output );

    }
    reader.close();
}
```

somehow on each pass through the loop, `colors.add(output);` is overwriting the ENTIRE colors list with the new value?
WTF?

**Comment by EMBTonkin** [comment]
Because 'add' is not the way to add things to the basic array type.  Looking at the official documentation I could not even find the add method.  It's probably since arrays have immutable lengths, so add would not make sense.  I would either convert to an ArrayList or use an index to index into the array.

**Comment by StrykeSlammerII** [comment]
Umm...  `colors` _was_ an `ArrayList<string[]>`, declared above the try block (but maybe still hiding?)

I figured it out on my way home from work though: `output` was _the same object_ each time, so I was adding a thing to the arraylist, changing that thing, and adding it again.
Whoops.

Fixed now, and just making sure the indexes match up with colorInfo.txt after reading.... then I'll commit the update to Analysis' constructor that reads in colorInfo.txt
Next commit after that will probably be getColorHex(String)

edit: (more ranting/rambling)
wait, no, that data structure won't work quite right: it doesn't allow for 1-indexed array, AND most of the time we want to look a color up by name directly rather than find the index and THEN look it up. Gonna need, what, a hash-thing mapping the colorName against a <Int, String> pair? Not sure that exists so I may have to do a quicky class for the <Int, String> instead :/
(Can I do an internal class for that? Since this data struct won't be known about outside this class, it should be OK right?)

**Comment by EMBTonkin** [comment]
... I obviously need to go back to first grade as my reading comprehension skills have dissipated, and now I fill like the stupid one.  

I'm glad you figured it out though.  We will have to be more careful about when Java passes copies of an object or pointers of an object.

About the hash mapping by color name, you can totally do that (I looked it up before we started everything since I knew we would need to do it.  )  When you make a hashmap you can set the key of a certain value, so you can set the color data (hex value and number) to the key of it's name.  In python there's a data structure called a dictionary that functions like this, I'm describing a Java equivalent.  

Color is going to need a lot of thought put into it since it will involve some strange math to get the proper color ranges between too colors.  Plus the whole color wheel update is looming color every day, but that should not affect too much.

**Comment by StrykeSlammerII** [comment]
Most recently I'm used to PHP's arrays that are more like dictionary with some extra frills, so finding the right class is a bit annoying XD thx for the tips.
The only thing I'm uncertain of yet is whether a Java hashmap will let us have a pair of values returned per key lookup, or if we'd need two hashmaps for that... or a wrapper class for the color data-pair.

and for testing, I guess I just need to make sure the color thing "works right" with an edited version of colorInfo.txt? I'm intending to make it robust though since there WILL be a color expansion :)
some quick brainstorming indicates the math won't be terrible--just check if we're doing everything from A to B, or everything 0 to A + B to end (and can figure that out by comparing A minus B to colorwheel.size / 2, or summat like that)

**Comment by StrykeSlammerII** [comment]
after changing to a TreeMap<String, Object[]> implementation (because there just aren't any _really_ useful map types) I'm gonna go ahead and try two Maps instead: One that keys on the color name, and the other that keys on index.

Because using just name as Key sorts by name (if at all) and that makes color math difficult.

...shoot, no, that doesn't give a good way to reverse-index from color name to index. So, um... I guess I'm gonna tag in a second map on top of the <String, Object[]> one, that is <Integer, String> for sort-by-number.
None of this stuff should be available outside of Analysis class so it shouldn't be a big deal, right? XD

**Comment by EMBTonkin** [comment]
No, the math is not really that bad, I was just confused by what numbers ended up being the right ones the first time I figured it out.  In python you can negative index arrays, so it was just figuring out which color to start with and then subtracting one from the index in a list of colors.

Here's a thought I had regarding the color index problem: we could make a Color object that holds the colors name, hex value, number value, and a pointer to the next color in the wheel (or just the next color's name).  Then, we can store all that stuff in one hashmap with name keys.  We get two colors, index by name to fine the color's number values, do the math to figure out which one to start with, and them because we implemented some sort of iterable interface (or just using a while loop), we can chug along getting the next color and then stop when we get to the last color.  I think that will do what we need it to do.  Although I see you have already implemented something so I am sorry I am too late with this.

Data won't be available outside of Analysis, so as long as the functions return the right values and we're not embarrassed by the internal structure it's fine.

**Comment by StrykeSlammerII** [comment]
I was trying to avoid making a data-only class, but it is something I considered :)
the colorwheel is small enough that it shouldn't cause any memory- or speed- efficiency issues either way.
using a cyclical linked list makes sense though! I shoulda thought of that Xp  (finding the inital color that way could be slow, but again--the colorwheel shouldn't be a bottleneck.)

I may go back and change the Treemap to a Hashmap but the immediate issue I think is working so I'm gonna close this issue :)
